---SELECT DISTINCT BRANCH_NAME FROM LOAN;
---SELECT LOAN_NUMBER FROM LOAN WHERE BRANCH_NAME='PERRYRIDGE' AND AMOUNT>1200;
---SELECT CUSTOMER_NAME, BORROWER.LOAN_NUMBER, AMOUNT FROM BORROWER,LOAN WHERE BORROWER.LOAN_NUMBER = LOAN.LOAN_NUMBER AND BRANCH_NAME ='PERRYRIDGE';
---select loan_number, branch_name, amount*100 from loan;
---select * from borrower, loan;
---SELECT CUSTOMER_NAME, BORROWER.LOAN_NUMBER AS LOAN_ID, AMOUNT FROM BORROWER,LOAN
---WHERE BORROWER.LOAN_NUMBER = LOAN.LOAN_NUMBER;
---SELECT DISTINCT T.BRANCH_NAME FROM BRANCH T, BRANCH S WHERE T.ASSETS > S.ASSETS AND S.BRANCh_CITY = 'Brooklyn';
---SELECT AVG(BALANCE) FROM ACCOUNT WHERE BRANCH_NAME='Perryridge';
---SELECT AVG(BALANCE) FROM ACCOUNT GROUP BY BRANCH.BRANCH_CITY;
---(SELECT distinct CUSTOMER_NAME FROM ACCOUNT, DEPOSITOR WHERE BRANCH_NAME='Perryridge') 
---INTERSECT (SELECT distinct CUSTOMER_NAME FROM BORROWER,LOAN WHERE BORROWER.LOAN_NUMBER=LOAN.LOAN_NUMBER and BRANCH_NAME='Perryridge');
---SELECT CUSTOMER_NAME FROM DEPOSITOR UNION SELECT CUSTOMER_NAME FROM BORROWER;
SELECT DISTINCT CUSTOMER_NAME FROM BORROWER, LOAN WHERE BORROWER.LOAN_NUMBER=LOAN.LOAN_NUMBER AND BRANCH_NAME='Perryridge' AND (CUSTOMER_NAME) IN (SELECT BRANCH_NAME FROM DEPOSITOR, ACCOUNT WHERE DEPOSITOR.ACCOUNT_NUMBER=ACCOUNT.ACCOUNT_NUMBER AND BRANCH_NAME='Perryridge'); 



