CREATE OR REPLACE PROCEDURE query_emp(p_id in EMPLOYEES.EMPLOYEE_ID%TYPE, 
p_name OUT EMPLOYEES.LAST_NAME%TYPE, p_salary OUT EMPLOYEES.SALARY%TYPE) IS 
BEGIN
	SELECT LAST_NAME, SALARY INTO p_name, p_salary
	FROM EMPLOYEES
	WHERE EMPLOYEE_ID = p_id;
END query_emp;
/
