/*CREATE OR REPLACE PROCEDURE raise_salary(p_id in EMPLOYEES.EMPLOYEE_id%TYPE, p_percent IN NUMBER)
IS BEGIN
	UPDATE EMPLOYEES
	SET SALARY = SALARY * (1+p_percent/100)
	WHERE EMPLOYEE_ID = p_id;
END raise_salary;
/*/

CREATE OR REPLACE PROCEDURE query_emp(p_id in EMPLOYEES.EMPLOYEE_id%TYPE, 
p_name OUT EMPLOYEES.LAST_NAME%TYPE, p_salary OUT EMPLOYEES.SALARY%TYPE) IS 
BEGIN
	SELECT LAST_NAME, SALARY INTO p_name, p_salary
	FROM EMPLOYEES
	WHERE EMPLOYEE_ID = p_id;
END quere_emp;
/

